### ISSUE TITLE
Most documentation from the docs directory is missing.

### ISSUE THREAD

**Issue by nihz0** [IstariTheWise/RAID-MANAGER#1]
Is the docs directory supposed to contain some or most of what's in https://github.com/Illydth/wowraidmanager/tree/master/docs?

**Comment by Istari** [comment]
Most/All of that content is beyond historical it is simply irrelevant to the current code.  I am working on a better credits/contributions/history plan incorporating what there was that is still applicable.

**Comment by nihz0** [comment]
I understand.  It was still useful to me to figure out the version of php and the db I needed to use.
